package mi.email.way2.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MAIL_BEAN.
 */
public class MailBean {

	private Long id;
    private String messageId;	//邮件id
    private String subject;		//发送方
    private String from;		//来源
    private String content;		//内容
    private String toAddress;	//接收方
    private String ccAddress;	//抄送
    private String bccAddress;	//加密抄送
    private Boolean replySign;	//回执
    private Boolean containAttach;	//包含附件

    public MailBean() {
    }

    public MailBean(Long id) {
        this.id = id;
    }

    public MailBean(Long id, String messageId, String subject, String from, String content, String toAddress, String ccAddress, String bccAddress, Boolean replySign, Boolean containAttach) {
        this.id = id;
        this.messageId = messageId;
        this.subject = subject;
        this.from = from;
        this.content = content;
        this.toAddress = toAddress;
        this.ccAddress = ccAddress;
        this.bccAddress = bccAddress;
        this.replySign = replySign;
        this.containAttach = containAttach;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getToAddress() {
        return toAddress;
    }

    public void setToAddress(String toAddress) {
        this.toAddress = toAddress;
    }

    public String getCcAddress() {
        return ccAddress;
    }

    public void setCcAddress(String ccAddress) {
        this.ccAddress = ccAddress;
    }

    public String getBccAddress() {
        return bccAddress;
    }

    public void setBccAddress(String bccAddress) {
        this.bccAddress = bccAddress;
    }

    public Boolean getReplySign() {
        return replySign;
    }

    public void setReplySign(Boolean replySign) {
        this.replySign = replySign;
    }

    public Boolean getContainAttach() {
        return containAttach;
    }

    public void setContainAttach(Boolean containAttach) {
        this.containAttach = containAttach;
    }
}
