package mi.email.way2.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import mi.email.way2.model.MailBean;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mailBeanDaoConfig;

    private final MailBeanDao mailBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mailBeanDaoConfig = daoConfigMap.get(MailBeanDao.class).clone();
        mailBeanDaoConfig.initIdentityScope(type);

        mailBeanDao = new MailBeanDao(mailBeanDaoConfig, this);

        registerDao(MailBean.class, mailBeanDao);
    }
    
    public void clear() {
        mailBeanDaoConfig.getIdentityScope().clear();
    }

    public MailBeanDao getMailBeanDao() {
        return mailBeanDao;
    }

}
